### ISSUE TITLE
cool!

### ISSUE THREAD

**Issue by aquynh** [Rewzilla/asemu#1]
this is so cool! do you have any screenshot to share?

keep it up, cheers!

**Comment by Rewzilla** [comment]
Hi, thanks!! :)  Just a little side project that I've started working
on.  It's VERY young, not even really functional yet, but I hope to
someday build it into something great.  I've added a screenshot to the
README for you.  I also added a deps.sh script to build all the
dependencies if you want to try it out. 

Thank you for the note! 

Andrew 

On 2017-09-21 08:02, Nguyen Anh Quynh wrote:

> this is so cool! do you have any screenshot to share? 
> 
> keep it up, cheers! 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

 

Links:
------
[1] https://github.com/Rewzilla/asemu/issues/1
[2]
